#!/usr/bin/python3

# imports
from setuptools import setup, find_packages

setup(name='ccot',
      version='1.0',
      description='CCOT research code for conditional optimal transport experiments',
      url='',
      author='CCOT contributors',
      author_email='',
      packages=find_packages(),
      test_suite='nose.collector',
      tests_require=['nose'],
      install_requires=[
          'numpy>=1.24.4',
          'torch>=2.0.1',
          'jax>=0.4.13',
          'jaxlib>=0.4.13',
          'ott-jax>=0.4.2',
          'pandas>=2.0.3',
          'scipy>=1.11.1',
          'scikit-learn>=1.3.0',
          'scanpy>=1.9.3',
          'anndata>=0.7.6',
          'ml-collections>=0.1.0',
          'matplotlib>=3.7.2',
          'seaborn>=0.12.2',
          'gitpython>=3.1.31',
          'pytables>=3.8.0',
          'absl-py>=1.0.0',
          'PyYAML>=5.4.0',
          'umap-learn>=0.5.3',
          'geomloss>=0.2.6',
          'torchmetrics>=0.11.0',
          'optuna>=3.1.0',
          'numba>=0.56.0',
          'openpyxl>=3.0.10',
      ],
      zip_safe=False)
